options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/impactful-arbor-399720/employee-mngnt/employee-mngnt-image:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/impactful-arbor-399720/employee-mngnt/employee-mngnt-image:$COMMIT_SHA']

  # Step 3: Deploy to Google Cloud Run (GCR)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
        - 'run'
        - 'deploy'
        - 'employee-management'
        - '--image'
        - 'us-central1-docker.pkg.dev/impactful-arbor-399720/employee-mngnt/employee-mngnt-image:$COMMIT_SHA'
        - '--platform'
        - 'managed'
        - '--region'
        - 'us-central1'
        - '--allow-unauthenticated'
        - '--port=8080'

timeout: '2800s'

images:
  - 'us-central1-docker.pkg.dev/impactful-arbor-399720/employee-mngnt/employee-mngnt-image:$COMMIT_SHA'