spring.application.name=employee-mgmnt

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?schema=employee_message
spring.datasource.username=postgres
spring.datasource.password=test


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger config

springdoc.swagger-ui.url=/swagger.YAML
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


status.statusValues=remove,delete
server.port=8080

spring.security.user.name=sunil
spring.security.user.password=test

spring.profiles.active=${SPRING_PROFILES_ACTIVE}