#spring.application.name=employee-mgmnt
#
#spring.datasource.url=jdbc:postgresql://dpg-d180c8odl3ps739a4i5g-a:5432/employee_dev?currentSchema=employee_message
#spring.datasource.username=employee_dev_user
#spring.datasource.password=${DATASOURCE_PASSWORD}
#
##Use this url to run dev environment in local
##jdbc:postgresql://dpg-d180c8odl3ps739a4i5g-a.singapore-postgres.render.com:5432/employee_dev?currentSchema=employee_message
#
#spring.jpa.show-sql=true
#
## Swagger config
#
#springdoc.swagger-ui.url=/swagger.YAML
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#
#
#status.statusValues=remove,delete
#server.port=8080
#
#spring.security.user.name=sunil
#spring.security.user.password=test